name: Publish Javadocs and Spike Config Schema

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  JAVA_VERSION: "17"
  SCHEMA_PATH: "src/main/resources/config-schema.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Javadocs
        run: ./gradlew --no-daemon javadoc

      - name: Verify schema exists
        run: |
          if [ ! -f "${{ env.SCHEMA_PATH }}" ]; then
            echo "Schema not found at ${{ env.SCHEMA_PATH }}. Update SCHEMA_PATH or add the file."
            exit 1
          fi

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Prepare site content
        run: |
          set -euo pipefail
          mkdir -p site/javadoc
          mkdir -p site/schema
          cp -r build/docs/javadoc/* site/javadoc/
          cp "${{ env.SCHEMA_PATH }}" "site/schema/spike-config.schema.json"

          # Minimal index with handy links
          cat > site/index.html << 'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Project Docs</title>
            <style>
              body { font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; padding: 2rem; line-height: 1.5; }
              h1 { margin-top: 0; }
              code { background: #f2f2f2; padding: 0.1rem 0.3rem; border-radius: 4px; }
              ul { margin: 0.75rem 0 0 1.25rem; }
            </style>
          </head>
          <body>
            <h1>Documentation</h1>
            <ul>
              <li><a href="./javadoc/">Javadocs</a></li>
              <li>Spike Config JSON Schema: <a href="./schema/spike-config.schema.json"><code>schema/spike-config.schema.json</code></a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Upload static site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
